<a href="https://colab.research.google.com/github/ddekun/PyTorch_framework/blob/lesson1/lesson1/hw1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Фреймворк PyTorch для разработки искусственных нейронных сетей

### Урок 1. Основные понятия и структуры PyTorch

Создайте случайный FloatTensor размера 3x4x5

Выведите его форму (shape)

Приведите его к форме 6х10

Создайте случайный IntTensor размера 10

Умножьте созданный FloatTensor на созданный IntTensor поэлементно

Умножьте тензор матрично на себя, чтобы результат был размерности 6x6

Подсказка: .dot может не подойти

Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)

Создайте единичный тензор размера 5x6

Переведите его в формат numpy

In [1]:
import torch

In [2]:
# 1. Создайте случайный FloatTensor размера 3x4x5

x = torch.randn(3, 4, 5)
x, x.type()

(tensor([[[ 0.9482,  0.0660, -0.5293, -1.3641, -1.3941],
          [-0.4267,  0.1033, -0.7336, -0.8792, -1.2097],
          [-1.7229,  0.4023, -1.4431,  1.1608,  0.7541],
          [ 1.7386,  0.3163, -0.1360, -0.8178,  1.0720]],
 
         [[-0.8304,  1.0878, -1.3086,  1.1158, -0.3920],
          [-0.6660, -0.1270,  0.5860, -1.2018,  0.5475],
          [ 0.0630, -0.4564,  1.3766, -0.5334,  1.3642],
          [ 0.5864,  0.6006,  1.5115, -2.2085, -0.9250]],
 
         [[ 0.7432, -0.6280, -0.7483, -0.0975,  0.5778],
          [ 1.4053,  0.9843,  0.2359, -2.0276, -0.5857],
          [-0.0740, -1.3562, -0.0484,  0.4201,  0.5969],
          [-0.2380, -0.7197, -1.6234,  1.0274,  1.0600]]]),
 'torch.FloatTensor')

In [3]:
# 2. Выведите его форму (shape)
x.shape

torch.Size([3, 4, 5])

In [4]:
# 3. Приведите его к форме 6х10
x = x.reshape(6, 10)
x

tensor([[ 0.9482,  0.0660, -0.5293, -1.3641, -1.3941, -0.4267,  0.1033, -0.7336,
         -0.8792, -1.2097],
        [-1.7229,  0.4023, -1.4431,  1.1608,  0.7541,  1.7386,  0.3163, -0.1360,
         -0.8178,  1.0720],
        [-0.8304,  1.0878, -1.3086,  1.1158, -0.3920, -0.6660, -0.1270,  0.5860,
         -1.2018,  0.5475],
        [ 0.0630, -0.4564,  1.3766, -0.5334,  1.3642,  0.5864,  0.6006,  1.5115,
         -2.2085, -0.9250],
        [ 0.7432, -0.6280, -0.7483, -0.0975,  0.5778,  1.4053,  0.9843,  0.2359,
         -2.0276, -0.5857],
        [-0.0740, -1.3562, -0.0484,  0.4201,  0.5969, -0.2380, -0.7197, -1.6234,
          1.0274,  1.0600]])

In [5]:
# 4. Создайте случайный IntTensor размера 10
a = torch.randint(10, size=(10,)).type(torch.IntTensor)
a, a.type()

(tensor([2, 4, 5, 2, 0, 7, 3, 6, 0, 7], dtype=torch.int32), 'torch.IntTensor')

In [6]:
# 5. Умножьте созданный FloatTensor на созданный IntTensor поэлементно
xa = x * a
xa

tensor([[ 1.8964,  0.2639, -2.6467, -2.7281, -0.0000, -2.9870,  0.3099, -4.4013,
         -0.0000, -8.4678],
        [-3.4458,  1.6094, -7.2156,  2.3216,  0.0000, 12.1704,  0.9490, -0.8158,
         -0.0000,  7.5042],
        [-1.6608,  4.3513, -6.5431,  2.2316, -0.0000, -4.6623, -0.3809,  3.5159,
         -0.0000,  3.8328],
        [ 0.1260, -1.8255,  6.8829, -1.0669,  0.0000,  4.1051,  1.8017,  9.0692,
         -0.0000, -6.4748],
        [ 1.4864, -2.5119, -3.7415, -0.1950,  0.0000,  9.8369,  2.9528,  1.4156,
         -0.0000, -4.1001],
        [-0.1481, -5.4250, -0.2419,  0.8402,  0.0000, -1.6663, -2.1592, -9.7403,
          0.0000,  7.4197]])

In [7]:
# 6. Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
# Подсказка: .dot может не подойти

xa_xa = xa @ xa.T
xa_xa

tensor([[ 118.2067,  -89.3575,  -24.8938,  -12.3419,   12.6110,  -19.0135],
        [ -89.3575,  277.9163,   33.9088,  -59.8293,  107.9793,   36.7717],
        [ -24.8938,   33.9088,  118.4180,  -68.3251,  -47.0782,  -17.1179],
        [ -12.3419,  -59.8293,  -68.3251,  196.1330,   64.3161, -139.7855],
        [  12.6110,  107.9793,  -47.0782,   64.3161,  146.8539,  -52.8282],
        [ -19.0135,   36.7717,  -17.1179, -139.7855,  -52.8282,  187.5808]])

In [8]:
# 7. Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)

x = torch.tensor([1.], requires_grad=True)
z = torch.tensor([0.5], requires_grad=True)
t = torch.tensor([2.], requires_grad=True)

y = x**3 + z - 75*t

y.backward()

print('dy/dx: ', x.grad)
print('dy/dz: ', z.grad)
print('dy/dt: ', t.grad)

dy/dx:  tensor([3.])
dy/dz:  tensor([1.])
dy/dt:  tensor([-75.])


In [9]:
# 8. Создайте единичный тензор размера 5x6

t_ones = torch.ones(5, 6)
t_ones

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [10]:
# 9. Переведите его в формат numpy

t_ones = t_ones.numpy()
t_ones

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)